
[package]
edition = "2024"
name = "pico2w-template"
version = "0.1.0"
license = "MIT or Apache-2.0"

[dependencies]
defmt = "1"
defmt-rtt = "1"
embedded-hal = "1.0.0"
panic-probe = { version = "1", features = ["print-defmt"] }

[target."thumbv8m.main-none-eabihf".dependencies]
rp235x-hal = { version = "0.3", features = ["rt", "critical-section-impl"] }
